version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-db/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-sftp
    AIRFLOW_CONN_POSTGRES_DB: postgresql://airflow:airflow@postgres-db:5432/my_db_1
    AIRFLOW_CONN_SFTP_DEFAULT: sftp://ubuntu:ubuntu@sftp-server:22
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - data_vol:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  networks:
    - shared_infra

services:
  data-permissions:
    <<: *airflow-common
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - chown -R ${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0} /opt/airflow/data
    # profiles:
    #   - setup

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com \
          --password admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8090:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      data-permissions:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      data-permissions:
        condition: service_completed_successfully

networks:
  shared_infra:
    external: true
    name: shared_infra_net

volumes:
  data_vol:
